version: '3'
services:
  server:
    build: ./server
    ports:
     - "80:80"
    networks:
     - my-network
  client:
    build: ./client
    environment:
     - PASSWORD=${VALUE}
    depends_on:
     - server
    networks:
     - my-network
networks:
  
  my-network:
