version: '3'
services:
  server:
    build: ./server
    ports:
     - "80:80"
    networks:
     - my-network
  client:
    build: ./client
    ports:
     - "8080:8080"
#    depends_on:
#     - server
    networks:
     - my-network
networks:
  my-network:
